/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        // Calm new-tab + flashcard palette
        canvas: '#0c0b0a',
        card: '#161412',
        'card-hover': '#1e1c19',
        ink: '#ebe6e1',
        muted: '#8f877c',
        accent: '#e8c066',
        'accent-dim': '#a88432',
        success: '#2d9b6e',
        'success-dim': '#1e6b4c',
        error: '#c45c6a',
        'error-dim': '#8a3d47',
        border: '#2a2622',
        'border-strong': '#3d3830',

        // Aliases (legacy class names in modules)
        background: '#0c0b0a',
        surface: '#0c0b0a',
        'surface-container-low': '#161412',
        'surface-container': '#161412',
        'surface-container-high': '#1e1c19',
        'surface-container-highest': '#2a2622',
        'surface-bright': '#242120',
        'on-surface': '#ebe6e1',
        'on-surface-variant': '#8f877c',
        primary: '#ebe6e1',
        'primary-container': '#e8c066',
        'on-primary-container': '#3d3010',
        secondary: '#68dba9',
        'secondary-container': '#2d9b6e',
        'on-secondary-container': '#ebe6e1',
        'on-tertiary': '#8a3d47',
        'on-tertiary-container': '#c45c6a',
        'tertiary-container': '#2e1a1e',
        outline: '#3d3830',
        'outline-variant': '#2a2622',
      },
      maxWidth: {
        challenge: '400px',
        stats: '560px',
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        md: '20px',
        'container-padding': '24px',
        gutter: '16px',
        xl: '48px',
        lg: '32px',
        xs: '8px',
        sm: '12px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        editorial: ['Lora', 'Georgia', 'serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-word': ['Lora', 'Georgia', 'serif'],
        'display-sentence': ['Lora', 'Georgia', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'prompt-word': [
          '3.25rem',
          { lineHeight: '1.12', letterSpacing: '-0.01em', fontWeight: '500' },
        ],
        'prompt-sentence': [
          '1.625rem',
          { lineHeight: '1.45', letterSpacing: '0', fontWeight: '400' },
        ],
        'display-word': [
          '3.25rem',
          { lineHeight: '1.12', letterSpacing: '-0.01em', fontWeight: '500' },
        ],
        'display-sentence': [
          '1.625rem',
          { lineHeight: '1.45', letterSpacing: '0', fontWeight: '400' },
        ],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
