/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#151312',
        'on-tertiary': '#68001a',
        'on-tertiary-container': '#bc0036',
        'tertiary-fixed': '#ffdada',
        'on-primary-fixed-variant': '#574500',
        surface: '#151312',
        'secondary-fixed-dim': '#68dba9',
        'on-surface-variant': '#d0c6ae',
        'inverse-on-surface': '#33302e',
        'on-secondary': '#003825',
        'surface-tint': '#eac33e',
        'tertiary-container': '#ffcacc',
        secondary: '#68dba9',
        'on-surface': '#e8e1df',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#eac33e',
        background: '#151312',
        'surface-container-low': '#1d1b1a',
        'on-primary-container': '#715b00',
        'inverse-surface': '#e8e1df',
        'outline-variant': '#4d4635',
        'error-container': '#93000a',
        'primary-container': '#fcd34d',
        'on-tertiary-fixed-variant': '#920028',
        'on-primary': '#3c2f00',
        'surface-container': '#221f1e',
        'on-error': '#690005',
        tertiary: '#fff0f0',
        'on-secondary-fixed': '#002114',
        'surface-container-high': '#2c2928',
        'on-tertiary-fixed': '#40000c',
        primary: '#fff2d6',
        'secondary-container': '#25a475',
        'surface-container-highest': '#373433',
        'surface-bright': '#3c3837',
        'primary-fixed': '#ffe086',
        'surface-variant': '#373433',
        'on-background': '#e8e1df',
        'on-secondary-container': '#00311f',
        error: '#ffb4ab',
        'tertiary-fixed-dim': '#ffb3b6',
        'on-secondary-fixed-variant': '#005137',
        outline: '#99907b',
        'surface-container-lowest': '#100e0d',
        'secondary-fixed': '#85f8c4',
        'inverse-primary': '#735c00',
        'on-primary-fixed': '#231b00',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        md: '20px',
        'container-padding': '24px',
        gutter: '16px',
        xl: '48px',
        lg: '32px',
        xs: '8px',
        sm: '12px',
      },
      fontFamily: {
        'headline-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-word': ['Inter', 'sans-serif'],
        'display-sentence': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-word': [
          '48px',
          { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'display-sentence': [
          '24px',
          { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '500' },
        ],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
